import 'package:get/get.dart';

class MyLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "app_name": "Pomo Flutter",
          "get_started": "Get Started!",
          "next": "Next",
          "first_time_first_body": "Easy task & work management with pomo",
          "first_time_second_body": "Track your productivity & gain insights",
          "first_time_third_body": "Take a break and enjoy your coffee",
          "lets_in": "Let's you in",
          "sing_in_with_google": "Sign in with Google",
          "sing_in_with_github": "Sign in with Github",
          "sing_in_with_email": "Sign in with Email",
          "dont_have_account": "Don't have an account?",
          "sign_up": "Sign up",
          "sign_in": "Sign in",
          "already_have_account": "Already have an account?",
          "create_account": "Create an account",
          "sing_up": "Sign up",
          "or": "Or continue with",
          "accept_terms_and_conditions": "I accept the terms and conditions",
          "email": "Email",
          "password": "Password",
          "confirm_password": "Confirm password",
          "login_with_email": "Login yo your account",
          "forgot_password": "Forgot password?",
          "name_error":
              "Name must be at least 3 characters and without special characters",
          "email_error": "Email is not valid",
          "pass_error": "Password must be at least 6 characters",
          "confirm_pass_error": "Passwords do not match",
          "recover_password": "Recover password",
          "email_verification": "Email verification",
          "email_verification_text":
              "Check your email inbox and verify your account to continue.",
          "check_email_verification": "Continue",
          "not_received_email_verification":
              "Haven't received the verification email?",
          "resend_email_verification": "Resend email verification",
          "good_night": "Good night",
          "good_morning": "Good morning",
          "good_afternoon": "Good afternoon",
          "good_evening": "Good evening",
          "start_your_day": "It's going to be a great day, let's start!",
          "starting_your_daily_task": "You can do it! Let's go for it!",
          "keep_going": "Keep it up! You've already come a long way",
          "almost_there": "You've already passed the middle! Let's go!",
          "you_can_do_it": "You're almost there! Let's go!",
          "you_did_it": "You did it! Congratulations!",
          "statics_title": "Your Progress",
          "task_form_title": "New Task",
          "profile_title": "Your Profile",
          "calendar_title": "Calendar",
          "timer_title": "Timer",
          "task_completed": "Task completed!",
          "completed_tasks": "{completed} of {total} completed!",
          "today_task": "Today's Tasks",
          "see_all": "See All",
          "clear_done_tasks": "Clear finished",
          "add_new_task": "Add new",
          "mark_all_as_done": "Mark all as done",
          "no_task": "No tasks for today...",
          "task_form_button_clear": "Clear form",
          "task_form_button_save": "Save task",
          "task_form_input_title": "Task title",
          "task_form_input_description": "Task description",
          "task_form_input_date": "Task date",
          "task_form_input_time": "Task time",
          "task_form_input_category": "Task category",
          "task_form_input_color": "Task color",
          "task_form_input_count_working_session": "Working sessions",
          "task_form_input_time_working_session": "Working time",
          "task_form_input_time_break_session": "Break time",
          "task_form_input_time_long_break_session": "Long break time",
          "red_name": "Red",
          "orange_name": "Orange",
          "yellow_name": "Yellow",
          "green_name": "Green",
          "blue_name": "Blue",
          "purple_name": "Purple",
          "pink_name": "Pink",
          "work_name": "Work",
          "personal_name": "Personal",
          "shopping_name": "Shopping",
          "others_name": "Others",
          "task_name_error":
              "Name must not be empty and have less than 20 characters",
          "task_description_error":
              "Description must not be empty and have less than 100 characters",
          "default_working_config": "Default working configuration",
          "reset_config": "Reset configuration",
          "save_config": "Save configuration",
          "error_save_config_web":
              "The option to save the configuration is not available in the web version",
          "user_config": "User configuration",
          "logout": "Logout",
          "aparence_config": "Appearance configuration",
          "sessions_now": "{completed} of {total} sessions",
          "delete_task": "Delete task",
          "delete_task_message": "Are you sure you want to delete this task?",
          "confirm": "Confirm",
          "cancel": "Cancel",
          "task_stopped": "Task stopped",
          "congratulations_title": "Congratulations!",
          "congratulations_body":
              "You have successfully completed all of today's pomodoro tasks! Great job!",
          "view_statistics": "View statistics",
          "go_back": "Go back",
          "break": "Break",
          "today_statistics": "Today's statistics",
          "month_statistics": "Month statistics",
          "success_save_config": "Configuration saved successfully",
          "login_success": "Login success",
          "passwords_not_match": "Passwords do not match",
          "register_success": "Register success",
          "login_google_success": "Login with Google success",
          "password_reset_send_success": "Password reset send success",
        },
        'es_ES': {
          "app_name": "Pomo Flutter",
          "get_started": "¡Empezemos!",
          "next": "Siguiente",
          "first_time_first_body":
              "Gestión fácil de tareas y trabajos con pomo",
          "first_time_second_body":
              "Realice un seguimiento de su productividad y obtenga información",
          "first_time_third_body": "Tómate un descanso y disfruta de tu café",
          "lets_in": "Vamos a empezar",
          "sing_in_with_google": "Inicia sesión con Google",
          "sing_in_with_github": "Inicia sesión con Github",
          "sing_in_with_email": "Inicia sesión con Email",
          "dont_have_account": "¿No tienes una cuenta?",
          "sign_up": "Regístrate",
          "sign_in": "Iniciar sesión",
          "already_have_account": "¿Ya tienes una cuenta?",
          "create_account": "Crea una cuenta",
          "sing_up": "Regístrate",
          "or": "O continua con",
          "accept_terms_and_conditions": "Acepto los términos y condiciones",
          "email": "Email",
          "password": "Contraseña",
          "confirm_password": "Confirmar contraseña",
          "login_with_email": "Inicia sesión en tu cuenta",
          "forgot_password": "¿Olvidaste tu contraseña?",
          "name_error":
              "El nombre debe tener al menos 3 caracteres y sin caracteres especiales",
          "email_error": "El email no es válido",
          "pass_error": "La contraseña debe tener al menos 6 caracteres",
          "confirm_pass_error": "Las contraseñas no coinciden",
          "recover_password": "Recuperar contraseña",
          "email_verification": "Verificación de email",
          "email_verification_text":
              "Revisa la bandeja de entrada de tu email y verifica tu cuenta para poder continuar.",
          "check_email_verification": "Continuar",
          "not_received_email_verification":
              "¿No has recibido el email de verificación?",
          "resend_email_verification": "Reenviar email de verificación",
          "good_night": "Buenas noches",
          "good_morning": "Buenos días",
          "good_afternoon": "Buenas tardes",
          "good_evening": "Buenas noches",
          "start_your_day": "¡Va a ser un gran día, empezemos!",
          "starting_your_daily_task": "¡Tú puedes! ¡Vamos a por ello!",
          "keep_going": "¡Sigue así! Ya has avanzado mucho",
          "almost_there": "¡Ya has pasado la mitad! ¡Vamos!",
          "you_can_do_it": "¡Ya casi lo tienes! ¡Vamos!",
          "you_did_it": "¡Lo has conseguido! ¡Enhorabuena!",
          "statics_title": "Tu Progreso",
          "task_form_title": "Nueva Tarea",
          "profile_title": "Tu Perfil",
          "calendar_title": "Calendario",
          "timer_title": "Temporizador",
          "task_completed": "¡Tarea completada!",
          "completed_tasks": "¡{completed} de {total} completadas!",
          "today_task": "Tareas de hoy",
          "see_all": "Ver Todas",
          "clear_done_tasks": "Borrar completadas",
          "add_new_task": "Añadir nueva",
          "mark_all_as_done": "Marcar todas como completadas",
          "no_task": "No hay tareas para hoy...",
          "task_form_button_clear": "Limpiar formulario",
          "task_form_button_save": "Guardar tarea",
          "task_form_input_title": "Título de la tarea",
          "task_form_input_description": "Descripción de la tarea",
          "task_form_input_date": "Fecha de la tarea",
          "task_form_input_time": "Hora de la tarea",
          "task_form_input_category": "Categoría de la tarea",
          "task_form_input_color": "Color de la tarea",
          "task_form_input_count_working_session": "Sesiones de trabajo",
          "task_form_input_time_working_session": "Tiempo de trabajo",
          "task_form_input_time_break_session": "Tiempo de descanso",
          "task_form_input_time_long_break_session": "Tiempo de descanso largo",
          "red_name": "Rojo",
          "orange_name": "Naranja",
          "yellow_name": "Amarillo",
          "green_name": "Verde",
          "blue_name": "Azul",
          "purple_name": "Morado",
          "pink_name": "Rosa",
          "work_name": "Trabajo",
          "personal_name": "Personal",
          "shopping_name": "Compras",
          "others_name": "Otros",
          "task_name_error":
              "El nombre debe no estar vacío y tener menos de 20 caracteres",
          "task_description_error":
              "La descripción debe no estar vacía y tener menos de 100 caracteres",
          "default_working_config": "Configuración de trabajo por defecto",
          "reset_config": "Restablecer configuración",
          "save_config": "Guardar configuración",
          "error_save_config_web":
              "La opción de guardar la configuración no está disponible en la versión web",
          "user_config": "Configuración de usuario",
          "logout": "Cerrar sesión",
          "aparence_config": "Configuración de apariencia",
          "sessions_now": "{completed} de {total} sesiones",
          "delete_task": "Borrar tarea",
          "delete_task_message":
              "¿Estás seguro de que quieres borrar esta tarea?",
          "confirm": "Confirmar",
          "cancel": "Cancelar",
          "task_stopped": "Tarea detenida",
          "congratulations_title": "¡Enhorabuena!",
          "congratulations_body":
              "¡Has completado con éxito todas las tareas pomodoro de hoy! ¡Buen trabajo!",
          "view_statistics": "Ver estadísticas",
          "go_back": "Volver ",
          "break": "Descanso",
          "today_statistics": "Estadísticas de hoy",
          "month_statistics": "Estadísticas del mes",
          "success_save_config": "Configuración guardada correctamente",
          "login_success": "Inicio de sesión correcto",
          "passwords_not_match": "Las contraseñas no coinciden",
          "register_success": "Registro correcto",
          "login_google_success": "Inicio de sesión con Google correcto",
          "password_reset_send_success":
              "Envío de restablecimiento de contraseña correcto",
        },
      };
}
